# Name that appears in github actions page
name: Deploy api-oxygen-raw to Cloud Run Functions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    # Only trigger workflow if the push or pull request was on branch 'main'
    branches:
      - 'main'
    # Only trigger workflow if the push or pull request contains commits with changes to anything in these directories/files
    paths:
      - '.github/workflows/api-oxygen-raw-deploy.yml'
      - 'pipes/api_oxygen_raw/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/api-oxygen-raw-deploy.yml'
      - 'pipes/api_oxygen_raw/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel | In this case we only have 1 job
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Defines permissions the .yml will have
    permissions:
      # Permission to read contents of repository | In this case it's used to read the github secrets such as GCP_PROJECT_ID or GCP_SA_KEY
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Clones repository code to github runner, so workflow can access the files
    - name: Checkout code
      uses: actions/checkout@v3

      # Authenticates to Google Cloud to recieve necessary permissions
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_SA_KEY }}    

      # Deploys the container image located in the Artifact Registry to Cloud Run with unauthenticated access permitted (so anyone with the url can access/trigger it)
    - name: Deploy to Google Cloud Run Functions
      run: |
        gcloud functions deploy api_oxygen_bq \
          --gen2 \
          --region=us-central1 \
          --allow-unauthenticated \
          --runtime=python310 \
          --source=./pipes/api_oxygen_raw/ \
          --trigger-http \
          --memory=1024Mi